apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-doc-summarizer-deployment
spec:
  selector:
    matchLabels:
      app: ai-doc-summarizer
  replicas: 2
  template:
    metadata:
      labels:
        app: ai-doc-summarizer
    spec:
      containers:
        - name: ai-doc-summarizer
          image: springbootstudy/ai-doc-summarizer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KUBECONFIG
              value: "C:/Users/Admin/kubeconfig"
